name: OpenFaasFn
run-name: Build OpenFaas Fn
on: [push]

              
            

jobs:
  Build-Open-Faas-Fn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: openfaas-setup-cli
        uses: goncalo-oliveira/openfaas-setup-cli@v1
      - run: faas-cli version
      - run: ls -all
      - run: faas-cli build -f echo.yml
