name: OpenFaasFn
run-name: Build OpenFaas Fn
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build-Open-Faas-Fn:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: openfaas-setup-cli
        uses: goncalo-oliveira/openfaas-setup-cli@v1

      # Docker
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # semantic versioning
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          use_api: true
          scheme: semver
          increment: patch

      # Build and push
      - run: FN_VERSION="${{ steps.version.outputs.version }}" faas-cli build -f echo.yml
      - run: "docker push ghcr.io/jmgoyesc/open-faas-echo-fn:${{ steps.version.outputs.version }}"

      # Create Verifiable Credential
      - name: Create Verifiable Credential with Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: node holder-client.js


