name: OpenFaasFn
run-name: Build OpenFaas Fn
on: [push]

              
            

jobs:
  Build-Open-Faas-Fn:
    runs-on: ubuntu-latest
    steps:
      - name: openfaas-setup-cli
        uses: goncalo-oliveira/openfaas-setup-cli@v1
      - run: faas-cli version
